### ISSUE TITLE
Is there an admin interface?

### ISSUE THREAD

**Issue by aendra-rininsland** [maccman/monocle#25]
Hi!
Really enjoying this project, have installed it for a professional link sharing site I and a colleague are launching.

Quick question, though — I'm setup as an admin via `irb` as per the instructions, but does that actually do anything? It doesn't seem like I have any more privileges than a regular user, insomuch that I don't seem to be able to delete posts or comments or anything.

Also and maybe related, but it doesn't seem like the invite system is fully-working — users who sign-up via Twitter or GitHub are given full posting privileges, without needing admin approval.

Any thoughts? Thanks!

**Comment by maccman** [comment]
Hi @aendrew - as an admin you can vote on anything multiple times.

I also removed the invite system, as I assumed most people wouldn't want it invite only.

**Comment by aendra-rininsland** [comment]
@maccman How do you manage posts, then? Say somebody posts something really spammy, how do you remove it? I tried doing it via irb (Using something like `Brisk::Models::Post[:iid=>x].delete`, but then I was getting errors about how the Vote models were dependent upon that entry and whatnot.

Would you like that ability built into the UI for admins? If so, I'm happy to build it — I can see it being a really useful feature if running a popular list. Please reopen this issue if so — thanks!

**Comment by FredSarmento** [comment]
@maccman any feedback about @aendrew topic? How could we delete posts?
