### ISSUE TITLE
Javascript file format

### ISSUE THREAD

**Issue by alper** [maccman/monocle#30]
I tried to get Monocle to run on django this afternoon but I couldn't figure out what this file format was:

```
//= require ./core/monocle
//= require ./compat/env
//= require ./compat/css
//= require ./compat/stubs
//= require ./compat/browser
//= require ./compat/gala
```

And how to get it to work.

**Comment by rajeshduggal** [comment]
See: https://github.com/sstephenson/sprockets#the-directive-processor

**Comment by alper** [comment]
Ok. Amazing the number of ways that a javascript project can be built.
